clear; clc; close all;

%% =========================================================
% FINAL SPLIT-PLOT RCBD LAYOUT
% Field = 10.00 m × 9.45 m
% 3 Blocks × 3 Irrigation × 3 Hybrids
% 12 plants/subplot = 4 rows × 3 plants
% Row spacing fixed at 0.75 m
%% =========================================================

%% UNIT CONVERSION
m2ft = 3.28084;
mf = @(x) sprintf('%.2f m (%.2f ft)', x, x*m2ft);

%% FIELD SIZE
fieldW = 10.00;
fieldL = 9.45;

%% DESIGN
nBlocks = 3;
nIrrig  = 3;
nHybrid = 3;

%% PLANTING GEOMETRY
nRows = 4;
plantsPerRow = 3;
plantsPerSubplot = nRows * plantsPerRow;clc


rowSpacingY   = 0.75;
plantSpacingX = 0.25;

%% ALLEYS
hybAlley   = 0.25;
irrAlley   = 1;
blockAlley = 0.30;

%% SUBPLOT SIZE
subplotW = (fieldW - (nBlocks-1)*blockAlley ...
    - nBlocks*(nHybrid-1)*hybAlley) / (nBlocks*nHybrid);

rowMarginY = 0.075;
subplotL = (nRows-1)*rowSpacingY + 2*rowMarginY;

plantMarginX = (subplotW - (plantsPerRow-1)*plantSpacingX)/2;

%% BLOCK SIZE
blockW = nHybrid*subplotW + (nHybrid-1)*hybAlley;
blockL = nIrrig*subplotL + (nIrrig-1)*irrAlley;

%% BUFFERS
sideBuffer  = (fieldW - (nBlocks*blockW + (nBlocks-1)*blockAlley))/2;
frontBuffer = (fieldL - blockL)/2;

if sideBuffer < -1e-6 || frontBuffer < -1e-6 || plantMarginX < 0
    error('Layout does not fit. Reduce alley width or subplot spacing.');
end

%% POSITIONS
bx = sideBuffer + (0:nBlocks-1)*(blockW + blockAlley);
by = frontBuffer*ones(1,nBlocks);

%% TREATMENTS
irrig = {'M1','M2','M3'};
irrigFull = {'100% ETc','75% ETc','50% ETc'};
hyb = {'H1','H2','H3'};

%% RANDOMIZATION
rng(10);

irrOrder = cell(nBlocks,1);
hybOrder = cell(nBlocks,nIrrig);

for b = 1:nBlocks
    irrOrder{b} = irrig(randperm(nIrrig));
    for m = 1:nIrrig
        hybOrder{b,m} = hyb(randperm(nHybrid));
    end
end

%% COLORS
col = containers.Map({'M1','M2','M3'}, ...
    {[0.82 0.92 0.78], [0.78 0.86 0.96], [0.95 0.82 0.82]});

%% TOTALS
totalPlots  = nBlocks*nIrrig*nHybrid;
totalPlants = totalPlots*plantsPerSubplot;

%% FIT DIMENSION CHECK
usedFieldW = nBlocks*blockW + (nBlocks-1)*blockAlley + 2*sideBuffer;
usedFieldL = blockL + 2*frontBuffer;

fitText = { ...
    '\bfFit Dimension Check', ...
    sprintf('Available field = %s × %s', mf(fieldW), mf(fieldL)), ...
    sprintf('Used layout = %s × %s', mf(usedFieldW), mf(usedFieldL)), ...
    sprintf('Remaining width = %s', mf(fieldW-usedFieldW)), ...
    sprintf('Remaining length = %s', mf(fieldL-usedFieldL)), ...
    sprintf('Side buffer each side = %s', mf(sideBuffer)), ...
    sprintf('End buffer each end = %s', mf(frontBuffer)), ...
    sprintf('Block fit = %s × %s', mf(blockW), mf(blockL)), ...
    sprintf('Subplot fit = %s × %s', mf(subplotW), mf(subplotL)), ...
    sprintf('Plant margin X = %s', mf(plantMarginX))};

%% =========================================================
% FIGURE 1: FULL FIELD LAYOUT
%% =========================================================
figure('Color','w','Position',[80 80 1550 850]);
hold on; axis equal; box on;

xlim([-0.2 fieldW+0.2]);
ylim([-0.2 fieldL+0.2]);

title({'Figure 1. Full Field Layout', ...
       'Split-Plot RCBD: 3 Blocks × 3 Irrigation × 3 Hybrids'}, ...
       'FontSize',14,'FontWeight','bold');

rectangle('Position',[0 0 fieldW fieldL], ...
    'EdgeColor','k','LineWidth',2);

for b = 1:nBlocks

    x0 = bx(b);
    y0 = by(b);

    rectangle('Position',[x0 y0 blockW blockL], ...
        'EdgeColor','k','LineWidth',1.6);

    text(x0+blockW/2,y0+blockL+0.12, ...
        sprintf('Block %d',b), ...
        'HorizontalAlignment','center','FontWeight','bold','FontSize',11);

    for m = 1:nIrrig

        yStrip = y0 + blockL - m*subplotL - (m-1)*irrAlley;
        M = irrOrder{b}{m};
        idxM = find(strcmp(irrig,M));

        rectangle('Position',[x0 yStrip blockW subplotL], ...
            'FaceColor',col(M),'EdgeColor','k','LineWidth',1.1);

        text(x0+0.04,yStrip+subplotL-0.15, ...
            sprintf('%s = %s',M,irrigFull{idxM}), ...
            'FontSize',7.8,'FontWeight','bold');

        Hlist = hybOrder{b,m};

        for h = 1:nHybrid

            xSub = x0 + (h-1)*(subplotW+hybAlley);

            rectangle('Position',[xSub yStrip subplotW subplotL], ...
                'EdgeColor','k','LineWidth',0.9);

            text(xSub+subplotW/2,yStrip+subplotL/2, ...
                Hlist{h}, ...
                'HorizontalAlignment','center','FontSize',10,'FontWeight','bold');

            px = xSub + plantMarginX + (0:plantsPerRow-1)*plantSpacingX;
            py = yStrip + rowMarginY + (0:nRows-1)*rowSpacingY;

            for r = 1:nRows
                plot([xSub xSub+subplotW],[py(r) py(r)], ...
                    'k--','LineWidth',0.7);

                for p = 1:plantsPerRow
                    scatter(px(p),py(r),14,[0 0.45 0],'filled');
                end
            end

            if h < nHybrid
                alleyX = xSub + subplotW;

                rectangle('Position',[alleyX yStrip hybAlley subplotL], ...
                    'FaceColor',[1 1 1], ...
                    'EdgeColor',[0.65 0.65 0.65], ...
                    'LineStyle',':');

                text(alleyX+hybAlley/2,yStrip+subplotL/2, ...
                    mf(hybAlley), ...
                    'Rotation',90, ...
                    'HorizontalAlignment','center', ...
                    'FontSize',6.5);
            end
        end

        if m < nIrrig
            alleyY = yStrip - irrAlley;

            rectangle('Position',[x0 alleyY blockW irrAlley], ...
                'FaceColor',[0.96 0.96 0.96], ...
                'EdgeColor',[0.65 0.65 0.65], ...
                'LineStyle',':');

            text(x0+blockW/2,alleyY+irrAlley/2, ...
                sprintf('%s moisture alley / worker access', mf(irrAlley)), ...
                'HorizontalAlignment','center','FontSize',7.3);
        end
    end

    if b < nBlocks
        alleyX = x0 + blockW;

        rectangle('Position',[alleyX y0 blockAlley blockL], ...
            'FaceColor',[0.96 0.96 0.96], ...
            'EdgeColor',[0.65 0.65 0.65], ...
            'LineStyle',':');

        text(alleyX+blockAlley/2,y0+blockL/2, ...
            sprintf('%s block gap', mf(blockAlley)), ...
            'Rotation',90,'HorizontalAlignment','center','FontSize',7);
    end
end

%% DETAILS BOX
details = { ...
    '\bfLayout Details', ...
    sprintf('Field = %s × %s', mf(fieldW), mf(fieldL)), ...
    'Design = split-plot RCBD', ...
    'Blocks = 3', ...
    'Irrigation = 3 main plots/block', ...
    'Hybrids = 3 subplots/main plot', ...
    sprintf('Subplot = %s × %s', mf(subplotW), mf(subplotL)), ...
    sprintf('Block = %s × %s', mf(blockW), mf(blockL)), ...
    'Planting = 4 rows × 3 plants', ...
    sprintf('Plants/subplot = %d',plantsPerSubplot), ...
    sprintf('Plant spacing = %s', mf(plantSpacingX)), ...
    sprintf('Row spacing = %s', mf(rowSpacingY)), ...
    sprintf('Hybrid alley = %s', mf(hybAlley)), ...
    sprintf('Moisture alley = %s', mf(irrAlley)), ...
    sprintf('Block gap = %s', mf(blockAlley)), ...
    sprintf('Side buffer = %s', mf(sideBuffer)), ...
    sprintf('End buffer = %s', mf(frontBuffer)), ...
    sprintf('Total plots = %d',totalPlots), ...
    sprintf('Total plants = %d',totalPlants)};

xlabel('Field width: meters');
ylabel('Field length: meters');
set(gca,'FontSize',10);

xlim([-0.2 fieldW+0.2]);
ylim([-0.2 fieldL+0.2]);

annotation('textbox',[0.76 0.05 0.27 0.46], ...
    'String',details, ...
    'FitBoxToText','on', ...
    'BackgroundColor','w', ...
    'EdgeColor','k', ...
    'LineWidth',1.1, ...
    'FontSize',7.2, ...
    'Interpreter','tex');

annotation('textbox',[0.76 0.62 0.27 0.27], ...
    'String',fitText, ...
    'FitBoxToText','on', ...
    'BackgroundColor',[1 1 0.92], ...
    'EdgeColor','k', ...
    'LineWidth',1.1, ...
    'FontSize',7.2, ...
    'Interpreter','tex');

hybridText = { ...
    '\bfHybrid Labels', ...
    'H1 = Channel 214-78DGVT2RIB', ...
    'H2 = DKC6595RB', ...
    'H3 = Pioneer P1151AM'};

annotation('textbox',[0.76 0.03 0.27 0.10], ...
    'String',hybridText, ...
    'FitBoxToText','on', ...
    'BackgroundColor',[0.94 1.00 0.94], ...
    'EdgeColor','k', ...
    'LineWidth',1.1, ...
    'FontSize',7.5, ...
    'Interpreter','tex');

exportgraphics(gcf,'Fig1_FullLayout_10m_RowSpacing075_m_ft.png','Resolution',400);

%% =========================================================
% FIGURE 2: ONE BLOCK DETAIL
%% =========================================================
figure('Color','w','Position',[120 80 850 850]);
hold on; axis equal; box on;

xlim([-0.35 blockW+0.75]);
ylim([-0.35 blockL+0.55]);

title({'Figure 2. One Block Detail', ...
      '3 Irrigation Main Plots × 3 Hybrid Subplots'}, ...
      'FontSize',14,'FontWeight','bold');

rectangle('Position',[0 0 blockW blockL], ...
    'EdgeColor','k','LineWidth',2);

for m = 1:nIrrig

    yStrip = blockL - m*subplotL - (m-1)*irrAlley;

    rectangle('Position',[0 yStrip blockW subplotL], ...
        'FaceColor',[0.92 0.92 0.92], ...
        'EdgeColor','k','LineWidth',1.1);

    for h = 1:nHybrid

        xSub = (h-1)*(subplotW+hybAlley);

        rectangle('Position',[xSub yStrip subplotW subplotL], ...
            'EdgeColor','k','LineWidth',1.0);

        text(xSub+subplotW/2,yStrip+subplotL/2, ...
            sprintf('H%d',h), ...
            'HorizontalAlignment','center','FontSize',11,'FontWeight','bold');

        px = xSub + plantMarginX + (0:plantsPerRow-1)*plantSpacingX;
        py = yStrip + rowMarginY + (0:nRows-1)*rowSpacingY;

        for r = 1:nRows
            plot([xSub xSub+subplotW],[py(r) py(r)], ...
                'k--','LineWidth',0.8);

            for p = 1:plantsPerRow
                scatter(px(p),py(r),22,[0 0.5 0],'filled');
            end
        end

        if h < nHybrid
            alleyX = xSub + subplotW;

            rectangle('Position',[alleyX yStrip hybAlley subplotL], ...
                'FaceColor',[1 1 1], ...
                'EdgeColor',[0.65 0.65 0.65], ...
                'LineStyle',':');

            text(alleyX+hybAlley/2,yStrip+subplotL/2, ...
                sprintf('%s hybrid alley', mf(hybAlley)), ...
                'Rotation',90, ...
                'HorizontalAlignment','center','FontSize',7);
        end
    end

    if m < nIrrig
        rectangle('Position',[0 yStrip-irrAlley blockW irrAlley], ...
            'FaceColor',[0.96 0.96 0.96], ...
            'EdgeColor',[0.65 0.65 0.65], ...
            'LineStyle',':');

        text(blockW/2,yStrip-irrAlley/2, ...
            sprintf('%s moisture alley / worker access', mf(irrAlley)), ...
            'HorizontalAlignment','center','FontSize',8);
    end
end

plot([0 blockW],[-0.18 -0.18],'k','LineWidth',1.4);
text(blockW/2,-0.32,sprintf('Block width = %s', mf(blockW)), ...
    'HorizontalAlignment','center','FontWeight','bold');

plot([blockW+0.18 blockW+0.18],[0 blockL],'k','LineWidth',1.4);
text(blockW+0.47,blockL/2,sprintf('Block length = %s', mf(blockL)), ...
    'Rotation',90,'HorizontalAlignment','center','FontWeight','bold');

blockFitText = { ...
    '\bfBlock Fit Details', ...
    sprintf('Block = %s × %s', mf(blockW), mf(blockL)), ...
    sprintf('3 irrigation strips = %s', mf(nIrrig*subplotL)), ...
    sprintf('2 moisture alleys = %s', mf(2*irrAlley)), ...
    sprintf('3 hybrid subplots = %s', mf(nHybrid*subplotW)), ...
    sprintf('2 hybrid alleys = %s', mf(2*hybAlley)), ...
    sprintf('Each subplot = %s × %s', mf(subplotW), mf(subplotL)), ...
    sprintf('Each moisture alley = %s', mf(irrAlley)), ...
    sprintf('Each hybrid alley = %s', mf(hybAlley))};

annotation('textbox',[0.70 0.12 0.28 0.30], ...
    'String',blockFitText, ...
    'FitBoxToText','on', ...
    'BackgroundColor',[1 1 0.92], ...
    'EdgeColor','k', ...
    'LineWidth',1.0, ...
    'FontSize',7.8, ...
    'Interpreter','tex');

xlabel('Hybrid direction: meters');
ylabel('Irrigation-strip direction: meters');
set(gca,'FontSize',10);

exportgraphics(gcf,'Fig2_BlockDetail_10m_RowSpacing075_m_ft.png','Resolution',400);

%% =========================================================
% FIGURE 3: SUBPLOT DETAIL
%% =========================================================
figure('Color','w','Position',[180 80 760 800]);
hold on; axis equal; box on;

xlim([-0.25 subplotW+0.70]);
ylim([-0.35 subplotL+0.45]);

title({'Figure 3. Subplot Detail', ...
       '4 Maize Rows × 3 Plants = 12 Plants'}, ...
       'FontSize',14,'FontWeight','bold');

rectangle('Position',[0 0 subplotW subplotL], ...
    'EdgeColor','k','LineWidth',2);

px = plantMarginX + (0:plantsPerRow-1)*plantSpacingX;
py = rowMarginY + (0:nRows-1)*rowSpacingY;

for r = 1:nRows
    plot([0 subplotW],[py(r) py(r)], ...
        'b--','LineWidth',1.2);

    for p = 1:plantsPerRow
        scatter(px(p),py(r),70,[0 0.55 0],'filled');
    end
end

plot([0 subplotW],[-0.12 -0.12],'k','LineWidth',1.5);
text(subplotW/2,-0.25,sprintf('Subplot width = %s', mf(subplotW)), ...
    'HorizontalAlignment','center','FontWeight','bold');

plot([subplotW+0.12 subplotW+0.12],[0 subplotL], ...
    'k','LineWidth',1.5);

text(subplotW+0.38,subplotL/2, ...
    sprintf('Subplot length = %s', mf(subplotL)), ...
    'Rotation',90,'HorizontalAlignment','center','FontWeight','bold');

text(subplotW/2,subplotL+0.12, ...
    '12 plants/subplot: 4 rows × 3 plants', ...
    'HorizontalAlignment','center','FontWeight','bold');

subplotFitText = { ...
    '\bfSubplot Fit Details', ...
    sprintf('Subplot = %s × %s', mf(subplotW), mf(subplotL)), ...
    sprintf('Rows = %d',nRows), ...
    sprintf('Plants/row = %d',plantsPerRow), ...
    sprintf('Row spacing = %s', mf(rowSpacingY)), ...
    sprintf('Plant spacing = %s', mf(plantSpacingX)), ...
    sprintf('Row margin Y = %s', mf(rowMarginY)), ...
    sprintf('Plant margin X = %s', mf(plantMarginX)), ...
    sprintf('Plants/subplot = %d',plantsPerSubplot)};

annotation('textbox',[0.65 0.12 0.30 0.22], ...
    'String',subplotFitText, ...
    'FitBoxToText','on', ...
    'BackgroundColor',[1 1 0.92], ...
    'EdgeColor','k', ...
    'LineWidth',1.0, ...
    'FontSize',8, ...
    'Interpreter','tex');

xlabel('Within-row direction: meters');
ylabel('Across-row direction: meters');
set(gca,'FontSize',10);

exportgraphics(gcf,'Fig3_SubplotDetail_10m_RowSpacing075_m_ft.png','Resolution',400);


%% =========================================================
% SAVE ALL OPEN FIGURES INTO ONE PDF
%% =========================================================
save_all_figures_pdf('Final_Field_Layout_All_Figures.pdf');

function save_all_figures_pdf(pdfname)

figs = findall(0,'Type','figure');
figs = flipud(figs);

if exist(pdfname,'file')
    delete(pdfname)
end

for k = 1:length(figs)
    exportgraphics(figs(k),pdfname, ...
        'Append',true, ...
        'ContentType','vector');
end

fprintf('All figures saved into: %s\n',pdfname);

end